#server:
#  address: 0.0.0.0
#  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/babybook?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #client-id
            client-secret: #client-secret
            authorization-grant-type: authorization_code
            redirect-uri: #callback uri
            scope:
              - profile
              - email
          naver:
            client-id: N2c7n4PQsoGdvlygyjta
            client-secret: EdkLCWzaWQ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/oauth2/callback/naver
            scope:
              - nickname
              - email
              - profile_image
          kakao:
            client-id: 08bd15ea0687b56740a477196e5ba0c3
            client-secret: hN2VCPkcfjjpn4cMXDorgsAKbAinuoGM
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/oauth2/callback/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            unlink-uri: https://accounts.google.com/o/oauth2/revoke
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            unlink-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
jwt:
  secretKey: swerjv09wau5v09q23u09
  signatureAlgorithm: HS256
  tokenExpired: 604800 #(sec) 7 days

client:
  origins: http://localhost:3000
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

management:
  endpoints:
    web:
      base-path: /application
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always
